apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - namespace.yaml
  - secretstore.yaml
  - externalsecret.yaml
  - clusterissuer.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: cert-manager
        namespace: cert-manager
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::445746982355:role/nebulosa-cert-manager"

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.20.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml
    includeCRDs: true
