apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nebulosa-internal
  namespace: envoy-gateway-system
spec:
  gatewayClassName: nebulosa-envoy-gw
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: nebulosa-internal
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
