apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/envoyproxy/gateway/releases/download/v1.7.2/install.yaml
  - gatewayclass.yaml

patches:
  - target:
      kind: Deployment
      name: envoy-gateway
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
