replicaCount: 1

resources:
  requests:
    cpu: 20m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 8080

rbac:
  create: true

serviceAccount:
  create: true

collectors:
  - deployments
  - pods
  - nodes
  - replicasets
  - statefulsets
  - daemonsets
  - jobs
  - cronjobs
  - namespaces
  - persistentvolumeclaims
  - services
  - resourcequotas
  - limitranges
