apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-secrets
  namespace: langfuse
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: langfuse
    kind: SecretStore
  target:
    name: langfuse-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: nebulosa/langfuse
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: langfuse
  namespace: langfuse
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: langfuse-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-oidc
  namespace: langfuse
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: authentik-aws-sm
    kind: ClusterSecretStore
  target:
    name: langfuse-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTH_AUTHENTIK_CLIENT_SECRET: "{{ .langfuse }}"
  data:
    - secretKey: langfuse
      remoteRef:
        key: /authentik/oidc-clients
        property: langfuse
