apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: langfuse-web
  namespace: langfuse
spec:
  parentRefs:
    - name: nebulosa-internal
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - langfuse.internal.cloudhaven.work
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: langfuse-web
          port: 3000
