apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: cluster-otel
  namespace: observability
spec:
  mode: daemonset
  args:
    log-level: debug

  image: otel/opentelemetry-collector-contrib:0.123.0

  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: HYPERDX_API_KEY
      valueFrom:
        secretKeyRef:
          name: hyperdx-secret
          key: HYPERDX_API_KEY

  volumeMounts:
    - name: varlogpods
      mountPath: /var/log/pods
      readOnly: true
    - name: dockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true

  volumes:
    - name: varlogpods
      hostPath:
        path: /var/log/pods
        type: DirectoryOrCreate
    - name: dockercontainers
      hostPath:
        path: /var/lib/docker/containers
        type: DirectoryOrCreate

  config:
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        start_at: end
        include_file_path: true
        operators:
          - type: container
            id: container-parser

      hostmetrics:
        collection_interval: 20s
        scrapers:
          cpu: {}
          memory: {}
          disk: {}
          filesystem: {}
          network: {}

    processors:
      k8sattributes:
        auth_type: serviceAccount
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.namespace.name
            - k8s.node.name
      batch: {}

    exporters:
      otlphttp:
        endpoint: "https://in-otel.hyperdx.io"
        compression: gzip
        headers:
          authorization: "${env:HYPERDX_API_KEY}"

    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [k8sattributes, batch]
          exporters: [otlphttp]
        metrics:
          receivers: [hostmetrics, kubeletstats]
          processors: [k8sattributes, batch]
          exporters: [otlphttp]
