apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: cluster-otel
  namespace: observability
spec:
  mode: daemonset

  image: otel/opentelemetry-collector-contrib:0.123.0

  presets:
    logsCollection:
      enabled: true
    kubernetesAttributes:
      enabled: true
    hostMetrics:
      enabled: true
    kubernetesClusterMetrics:
      enabled: true
    kubeletMetrics:
      enabled: true

  env:
    - name: HYPERDX_API_KEY
      valueFrom:
        secretKeyRef:
          name: hyperdx-secret
          key: HYPERDX_API_KEY

  config:
    exporters:
      otlphttp:
        endpoint: http://hyperdx-collector:4318
        headers:
          authorization: "${env:HYPERDX_API_KEY}"

    service:
      pipelines:
        logs:
          exporters: [otlphttp]
        metrics:
          exporters: [otlphttp]
