apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-otel-collector
rules:
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/proxy", "node/stats", "node/metrics"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes", "events", "resourcequotas", "services", "replicationcontrollers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "daemonsets", "deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-otel-collector
subjects:
  - kind: ServiceAccount
    name: cluster-otel-collector
    namespace: observability
  - kind: ServiceAccount
    name: cluster-event-collector-opentelemetry-collector
    namespace: observability
  - kind: ServiceAccount
    name: cluster-metrics-collector-opentelemetry-collector
    namespace: observability
