apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: pi-cluster-system-apps
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.7.0
    helm:
      releaseName: longhorn
      values: |
        defaultSettings:
          defaultDataPath: /var/lib/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
