apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
spec:
  project: pi-cluster-system-apps
  source:
    repoURL: https://github.com/Cloudhaven-IDP/K8s-Bootstrap.git
    targetRevision: main
    path: afo-pi-cluster/kustomize/system-apps/qdrant
  destination:
    server: https://kubernetes.default.svc
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
