apiVersion: v1
data:
  HYPERDX_API_KEY: NTM1OWY1NWYtNTQzNC00ODIwLTk0MGQtYjY2NTI3ZjJmNjMy
kind: Secret
metadata:
  creationTimestamp: "2025-12-07T20:13:55Z"
  name: hyperdx-secret
  namespace: observability
  resourceVersion: "1568922"
  uid: c3933b92-6f51-4152-a384-bd3463957e0a
type: Opaque
