apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: qdrant
  namespace: qdrant
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qdrant-api-key
  namespace: qdrant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: qdrant
    kind: SecretStore
  target:
    name: qdrant-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: /restricted/qdrant/management-api-key
