apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: qdrant
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::445746982355:role/nebulosa-qdrant-external-secrets
