apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: temporal-oidc
  namespace: temporal-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: authentik-aws-sm
    kind: ClusterSecretStore
  target:
    name: temporal-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TEMPORAL_AUTH_CLIENT_SECRET: "{{ .client_secret }}"
  data:
    - secretKey: client_secret
      remoteRef:
        key: /authentik/oidc-clients
        property: temporal
