ipam:
  mode: kubernetes

kubeProxyReplacement: false

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

operator:
  replicas: 1

envoy:
  enabled: false

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: false

ipv4:
  enabled: true
ipv6:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi
