fullnameOverride: node-exporter

service:
  port: 9100
  targetPort: 9100

tolerations:
  - effect: NoSchedule
    operator: Exists

hostNetwork: true
hostPID: true

resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 96Mi

prometheus:
  monitor:
    enabled: false

extraArgs:
  - --collector.processes
  - --collector.tcpstat
  - --collector.interrupts
  - --collector.mountstats
  - --collector.network_route
  - --collector.systemd
  - --collector.ksmd
  - --collector.logind
  - --collector.cpu.info
  - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
  - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
  - --collector.netdev.device-exclude=^(veth|docker|br-|cali|flannel|cni|tailscale|cilium).*$
