apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: SecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: /restricted/tailscale/operator/client-id
    - secretKey: client_secret
      remoteRef:
        key: /restricted/tailscale/operator/client-secret
