apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-operator-ssm-reader
  namespace: tailscale
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::445746982355:role/humboldt-tailscale-operator"
