apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app
  namespace: arc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: arc
    kind: SecretStore
  target:
    name: github-app
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: /restricted/cloudhaven/github/arc/app-id
    - secretKey: github_app_installation_id
      remoteRef:
        key: /restricted/cloudhaven/github/arc/installation-id
    - secretKey: github_app_private_key
      remoteRef:
        key: /restricted/cloudhaven/github/arc/private-key
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: arc
  namespace: arc
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: arc-sa
