apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pull
  namespace: arc
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: arc
    kind: SecretStore
  target:
    name: ghcr-pull
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"auth":"{{ printf "cloudhaven-idp:%s" .token | b64enc }}"}}}
  data:
    - secretKey: token
      remoteRef:
        key: /restricted/cloudhaven/github/arc/ghcr-pull-secrets
