apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana
    kind: SecretStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: /restricted/grafana/admin-user
    - secretKey: admin-password
      remoteRef:
        key: /restricted/grafana/admin-password
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: grafana
  namespace: observability
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: grafana-sa
