apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-bootstrap
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: authentik-aws-sm
    kind: ClusterSecretStore
  target:
    name: authentik-bootstrap
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .secret_key }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .bootstrap_password }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .bootstrap_token }}"
  data:
    - secretKey: secret_key
      remoteRef:
        key: /authentik/bootstrap
        property: secret_key
    - secretKey: bootstrap_password
      remoteRef:
        key: /authentik/bootstrap
        property: bootstrap_password
    - secretKey: bootstrap_token
      remoteRef:
        key: /authentik/bootstrap
        property: bootstrap_token
