apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: langfuse

resources:
  - namespace.yaml

helmCharts:
  - name: postgres-platform
    repo: https://cloudhaven-idp.github.io/GitOps
    version: 0.1.1
    releaseName: langfuse-pg
    namespace: langfuse
    valuesFile: values.yaml
