apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: temporal-system

resources:
  - namespace.yaml

configMapGenerator:
  - name: temporal-pg-init
    files:
      - post-init.sql=files/post-init.sql
    options:
      disableNameSuffixHash: true

helmCharts:
  - name: postgres-platform
    repo: https://cloudhaven-idp.github.io/GitOps
    version: 0.1.2
    releaseName: temporal-pg
    namespace: temporal-system
    valuesFile: values.yaml
